// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _shipMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createshipMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteshipMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getshipbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateshipMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getshiplistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getstatisticsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _equipshipMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getequipmentlistMw() []app.HandlerFunc {
	// your code...
	return nil
}
