// Code generated by hertz generator.

package api

import (
	"context"

	api "FZU-DB-ALPortManager/biz/model/api"
	"FZU-DB-ALPortManager/biz/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

func sendError(c *app.RequestContext, err error) {
	c.JSON(consts.StatusInternalServerError, &api.BaseResp{
		Code: 500,
		Msg:  err.Error(),
	})
}

func sendSuccess(c *app.RequestContext, msg string) {
	c.JSON(consts.StatusOK, &api.BaseResp{
		Code: 200,
		Msg:  msg,
	})
}

// CreateShip .
// @router /api/v1/ship [POST]
func CreateShip(ctx context.Context, c *app.RequestContext) {
	var req api.Ship
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := service.NewShipService(ctx).CreateShip(&req)
	if err != nil {
		sendError(c, err)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// GetShipByID .
// @router /api/v1/ship/:id [GET]
func GetShipByID(ctx context.Context, c *app.RequestContext) {
	var req struct {
		ID int64 `path:"id" v:"required"`
	}
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := service.NewShipService(ctx).GetShipByID(req.ID)
	if err != nil {
		c.JSON(consts.StatusNotFound, &api.BaseResp{Code: 404, Msg: "指挥官，没有找到这艘船喵..."})
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// GetShipList .
// @router /api/v1/ships [GET]
func GetShipList(ctx context.Context, c *app.RequestContext) {
	var req api.GetShipListReq
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := service.NewShipService(ctx).GetShipList(&req)
	if err != nil {
		sendError(c, err)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// UpdateShip .
// @router /api/v1/ship/:id [PUT]
func UpdateShip(ctx context.Context, c *app.RequestContext) {
	var req api.UpdateShipReq
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := service.NewShipService(ctx).UpdateShip(req.GetID(), req.GetShip())
	if err != nil {
		sendError(c, err)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// DeleteShip .
// @router /api/v1/ship/:id [DELETE]
func DeleteShip(ctx context.Context, c *app.RequestContext) {
	var req struct {
		ID int64 `path:"id" v:"required"`
	}
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	err := service.NewShipService(ctx).DeleteShip(req.ID)
	if err != nil {
		sendError(c, err)
		return
	}

	sendSuccess(c, "指挥官，舰船已成功退役喵...")
}

// GetStatistics .
// @router /api/v1/stats [GET]
func GetStatistics(ctx context.Context, c *app.RequestContext) {
	resp, err := service.NewShipService(ctx).GetStatistics()
	if err != nil {
		sendError(c, err)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// EquipShip .
// @router /api/v1/ship/:id/equip [PUT]
func EquipShip(ctx context.Context, c *app.RequestContext) {
	var req api.EquipShipReq
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := service.NewShipService(ctx).EquipShip(&req)
	if err != nil {
		sendError(c, err)
		return
	}

	// 返回装备好之后，最新的舰船状态！
	c.JSON(consts.StatusOK, resp)
}

// GetEquipmentList .
// @router /api/v1/equipments [GET]
func GetEquipmentList(ctx context.Context, c *app.RequestContext) {
	var req api.GetEquipmentListReq
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := service.NewShipService(ctx).GetEquipmentList(&req)
	if err != nil {
		sendError(c, err)
		return
	}

	c.JSON(consts.StatusOK, resp)
}
