// Code generated by hertz generator.

package main

import (
	"FZU-DB-ALPortManager/db"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	db.Init()
	h := server.Default()

	register(h)
	h.Spin()
}
