// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q             = new(Query)
	Equipment     *equipment
	ShipEquipment *shipEquipment
	ShipInfo      *shipInfo
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Equipment = &Q.Equipment
	ShipEquipment = &Q.ShipEquipment
	ShipInfo = &Q.ShipInfo
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:            db,
		Equipment:     newEquipment(db, opts...),
		ShipEquipment: newShipEquipment(db, opts...),
		ShipInfo:      newShipInfo(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Equipment     equipment
	ShipEquipment shipEquipment
	ShipInfo      shipInfo
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Equipment:     q.Equipment.clone(db),
		ShipEquipment: q.ShipEquipment.clone(db),
		ShipInfo:      q.ShipInfo.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Equipment:     q.Equipment.replaceDB(db),
		ShipEquipment: q.ShipEquipment.replaceDB(db),
		ShipInfo:      q.ShipInfo.replaceDB(db),
	}
}

type queryCtx struct {
	Equipment     *equipmentDo
	ShipEquipment *shipEquipmentDo
	ShipInfo      *shipInfoDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Equipment:     q.Equipment.WithContext(ctx),
		ShipEquipment: q.ShipEquipment.WithContext(ctx),
		ShipInfo:      q.ShipInfo.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
