// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"FZU-DB-ALPortManager/model"
)

func newShipInfo(db *gorm.DB, opts ...gen.DOOption) shipInfo {
	_shipInfo := shipInfo{}

	_shipInfo.shipInfoDo.UseDB(db, opts...)
	_shipInfo.shipInfoDo.UseModel(&model.ShipInfo{})

	tableName := _shipInfo.shipInfoDo.TableName()
	_shipInfo.ALL = field.NewAsterisk(tableName)
	_shipInfo.ID = field.NewUint(tableName, "id")
	_shipInfo.CreatedAt = field.NewTime(tableName, "created_at")
	_shipInfo.UpdatedAt = field.NewTime(tableName, "updated_at")
	_shipInfo.DeletedAt = field.NewTime(tableName, "deleted_at")
	_shipInfo.ShipName = field.NewString(tableName, "ship_name")
	_shipInfo.Rarity = field.NewString(tableName, "rarity")
	_shipInfo.ShipType = field.NewString(tableName, "ship_type")
	_shipInfo.Faction = field.NewString(tableName, "faction")
	_shipInfo.Level = field.NewInt(tableName, "level")
	_shipInfo.Stars = field.NewInt(tableName, "stars")
	_shipInfo.Equipments = shipInfoHasManyEquipments{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Equipments", "model.ShipEquipment"),
		Equipment: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Equipments.Equipment", "model.Equipment"),
		},
	}

	_shipInfo.fillFieldMap()

	return _shipInfo
}

type shipInfo struct {
	shipInfoDo

	ALL        field.Asterisk
	ID         field.Uint
	CreatedAt  field.Time
	UpdatedAt  field.Time
	DeletedAt  field.Time
	ShipName   field.String
	Rarity     field.String
	ShipType   field.String
	Faction    field.String
	Level      field.Int
	Stars      field.Int
	Equipments shipInfoHasManyEquipments

	fieldMap map[string]field.Expr
}

func (s shipInfo) Table(newTableName string) *shipInfo {
	s.shipInfoDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s shipInfo) As(alias string) *shipInfo {
	s.shipInfoDo.DO = *(s.shipInfoDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *shipInfo) updateTableName(table string) *shipInfo {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewTime(table, "deleted_at")
	s.ShipName = field.NewString(table, "ship_name")
	s.Rarity = field.NewString(table, "rarity")
	s.ShipType = field.NewString(table, "ship_type")
	s.Faction = field.NewString(table, "faction")
	s.Level = field.NewInt(table, "level")
	s.Stars = field.NewInt(table, "stars")

	s.fillFieldMap()

	return s
}

func (s *shipInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *shipInfo) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["ship_name"] = s.ShipName
	s.fieldMap["rarity"] = s.Rarity
	s.fieldMap["ship_type"] = s.ShipType
	s.fieldMap["faction"] = s.Faction
	s.fieldMap["level"] = s.Level
	s.fieldMap["stars"] = s.Stars

}

func (s shipInfo) clone(db *gorm.DB) shipInfo {
	s.shipInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s shipInfo) replaceDB(db *gorm.DB) shipInfo {
	s.shipInfoDo.ReplaceDB(db)
	return s
}

type shipInfoHasManyEquipments struct {
	db *gorm.DB

	field.RelationField

	Equipment struct {
		field.RelationField
	}
}

func (a shipInfoHasManyEquipments) Where(conds ...field.Expr) *shipInfoHasManyEquipments {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a shipInfoHasManyEquipments) WithContext(ctx context.Context) *shipInfoHasManyEquipments {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a shipInfoHasManyEquipments) Model(m *model.ShipInfo) *shipInfoHasManyEquipmentsTx {
	return &shipInfoHasManyEquipmentsTx{a.db.Model(m).Association(a.Name())}
}

type shipInfoHasManyEquipmentsTx struct{ tx *gorm.Association }

func (a shipInfoHasManyEquipmentsTx) Find() (result []*model.ShipEquipment, err error) {
	return result, a.tx.Find(&result)
}

func (a shipInfoHasManyEquipmentsTx) Append(values ...*model.ShipEquipment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a shipInfoHasManyEquipmentsTx) Replace(values ...*model.ShipEquipment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a shipInfoHasManyEquipmentsTx) Delete(values ...*model.ShipEquipment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a shipInfoHasManyEquipmentsTx) Clear() error {
	return a.tx.Clear()
}

func (a shipInfoHasManyEquipmentsTx) Count() int64 {
	return a.tx.Count()
}

type shipInfoDo struct{ gen.DO }

func (s shipInfoDo) Debug() *shipInfoDo {
	return s.withDO(s.DO.Debug())
}

func (s shipInfoDo) WithContext(ctx context.Context) *shipInfoDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s shipInfoDo) ReadDB() *shipInfoDo {
	return s.Clauses(dbresolver.Read)
}

func (s shipInfoDo) WriteDB() *shipInfoDo {
	return s.Clauses(dbresolver.Write)
}

func (s shipInfoDo) Session(config *gorm.Session) *shipInfoDo {
	return s.withDO(s.DO.Session(config))
}

func (s shipInfoDo) Clauses(conds ...clause.Expression) *shipInfoDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s shipInfoDo) Returning(value interface{}, columns ...string) *shipInfoDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s shipInfoDo) Not(conds ...gen.Condition) *shipInfoDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s shipInfoDo) Or(conds ...gen.Condition) *shipInfoDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s shipInfoDo) Select(conds ...field.Expr) *shipInfoDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s shipInfoDo) Where(conds ...gen.Condition) *shipInfoDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s shipInfoDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *shipInfoDo {
	return s.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (s shipInfoDo) Order(conds ...field.Expr) *shipInfoDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s shipInfoDo) Distinct(cols ...field.Expr) *shipInfoDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s shipInfoDo) Omit(cols ...field.Expr) *shipInfoDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s shipInfoDo) Join(table schema.Tabler, on ...field.Expr) *shipInfoDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s shipInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) *shipInfoDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s shipInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) *shipInfoDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s shipInfoDo) Group(cols ...field.Expr) *shipInfoDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s shipInfoDo) Having(conds ...gen.Condition) *shipInfoDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s shipInfoDo) Limit(limit int) *shipInfoDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s shipInfoDo) Offset(offset int) *shipInfoDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s shipInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *shipInfoDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s shipInfoDo) Unscoped() *shipInfoDo {
	return s.withDO(s.DO.Unscoped())
}

func (s shipInfoDo) Create(values ...*model.ShipInfo) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s shipInfoDo) CreateInBatches(values []*model.ShipInfo, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s shipInfoDo) Save(values ...*model.ShipInfo) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s shipInfoDo) First() (*model.ShipInfo, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShipInfo), nil
	}
}

func (s shipInfoDo) Take() (*model.ShipInfo, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShipInfo), nil
	}
}

func (s shipInfoDo) Last() (*model.ShipInfo, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShipInfo), nil
	}
}

func (s shipInfoDo) Find() ([]*model.ShipInfo, error) {
	result, err := s.DO.Find()
	return result.([]*model.ShipInfo), err
}

func (s shipInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ShipInfo, err error) {
	buf := make([]*model.ShipInfo, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s shipInfoDo) FindInBatches(result *[]*model.ShipInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s shipInfoDo) Attrs(attrs ...field.AssignExpr) *shipInfoDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s shipInfoDo) Assign(attrs ...field.AssignExpr) *shipInfoDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s shipInfoDo) Joins(fields ...field.RelationField) *shipInfoDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s shipInfoDo) Preload(fields ...field.RelationField) *shipInfoDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s shipInfoDo) FirstOrInit() (*model.ShipInfo, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShipInfo), nil
	}
}

func (s shipInfoDo) FirstOrCreate() (*model.ShipInfo, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShipInfo), nil
	}
}

func (s shipInfoDo) FindByPage(offset int, limit int) (result []*model.ShipInfo, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s shipInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s shipInfoDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s shipInfoDo) Delete(models ...*model.ShipInfo) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *shipInfoDo) withDO(do gen.Dao) *shipInfoDo {
	s.DO = *do.(*gen.DO)
	return s
}
