// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"FZU-DB-ALPortManager/model"
)

func newShipEquipment(db *gorm.DB, opts ...gen.DOOption) shipEquipment {
	_shipEquipment := shipEquipment{}

	_shipEquipment.shipEquipmentDo.UseDB(db, opts...)
	_shipEquipment.shipEquipmentDo.UseModel(&model.ShipEquipment{})

	tableName := _shipEquipment.shipEquipmentDo.TableName()
	_shipEquipment.ALL = field.NewAsterisk(tableName)
	_shipEquipment.ShipID = field.NewUint(tableName, "ship_id")
	_shipEquipment.SlotIndex = field.NewInt(tableName, "slot_index")
	_shipEquipment.EquipmentID = field.NewUint(tableName, "equipment_id")
	_shipEquipment.CreatedAt = field.NewTime(tableName, "created_at")
	_shipEquipment.Equipment = shipEquipmentBelongsToEquipment{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Equipment", "model.Equipment"),
	}

	_shipEquipment.fillFieldMap()

	return _shipEquipment
}

type shipEquipment struct {
	shipEquipmentDo

	ALL         field.Asterisk
	ShipID      field.Uint
	SlotIndex   field.Int
	EquipmentID field.Uint
	CreatedAt   field.Time
	Equipment   shipEquipmentBelongsToEquipment

	fieldMap map[string]field.Expr
}

func (s shipEquipment) Table(newTableName string) *shipEquipment {
	s.shipEquipmentDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s shipEquipment) As(alias string) *shipEquipment {
	s.shipEquipmentDo.DO = *(s.shipEquipmentDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *shipEquipment) updateTableName(table string) *shipEquipment {
	s.ALL = field.NewAsterisk(table)
	s.ShipID = field.NewUint(table, "ship_id")
	s.SlotIndex = field.NewInt(table, "slot_index")
	s.EquipmentID = field.NewUint(table, "equipment_id")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *shipEquipment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *shipEquipment) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["ship_id"] = s.ShipID
	s.fieldMap["slot_index"] = s.SlotIndex
	s.fieldMap["equipment_id"] = s.EquipmentID
	s.fieldMap["created_at"] = s.CreatedAt

}

func (s shipEquipment) clone(db *gorm.DB) shipEquipment {
	s.shipEquipmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s shipEquipment) replaceDB(db *gorm.DB) shipEquipment {
	s.shipEquipmentDo.ReplaceDB(db)
	return s
}

type shipEquipmentBelongsToEquipment struct {
	db *gorm.DB

	field.RelationField
}

func (a shipEquipmentBelongsToEquipment) Where(conds ...field.Expr) *shipEquipmentBelongsToEquipment {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a shipEquipmentBelongsToEquipment) WithContext(ctx context.Context) *shipEquipmentBelongsToEquipment {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a shipEquipmentBelongsToEquipment) Model(m *model.ShipEquipment) *shipEquipmentBelongsToEquipmentTx {
	return &shipEquipmentBelongsToEquipmentTx{a.db.Model(m).Association(a.Name())}
}

type shipEquipmentBelongsToEquipmentTx struct{ tx *gorm.Association }

func (a shipEquipmentBelongsToEquipmentTx) Find() (result *model.Equipment, err error) {
	return result, a.tx.Find(&result)
}

func (a shipEquipmentBelongsToEquipmentTx) Append(values ...*model.Equipment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a shipEquipmentBelongsToEquipmentTx) Replace(values ...*model.Equipment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a shipEquipmentBelongsToEquipmentTx) Delete(values ...*model.Equipment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a shipEquipmentBelongsToEquipmentTx) Clear() error {
	return a.tx.Clear()
}

func (a shipEquipmentBelongsToEquipmentTx) Count() int64 {
	return a.tx.Count()
}

type shipEquipmentDo struct{ gen.DO }

func (s shipEquipmentDo) Debug() *shipEquipmentDo {
	return s.withDO(s.DO.Debug())
}

func (s shipEquipmentDo) WithContext(ctx context.Context) *shipEquipmentDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s shipEquipmentDo) ReadDB() *shipEquipmentDo {
	return s.Clauses(dbresolver.Read)
}

func (s shipEquipmentDo) WriteDB() *shipEquipmentDo {
	return s.Clauses(dbresolver.Write)
}

func (s shipEquipmentDo) Session(config *gorm.Session) *shipEquipmentDo {
	return s.withDO(s.DO.Session(config))
}

func (s shipEquipmentDo) Clauses(conds ...clause.Expression) *shipEquipmentDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s shipEquipmentDo) Returning(value interface{}, columns ...string) *shipEquipmentDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s shipEquipmentDo) Not(conds ...gen.Condition) *shipEquipmentDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s shipEquipmentDo) Or(conds ...gen.Condition) *shipEquipmentDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s shipEquipmentDo) Select(conds ...field.Expr) *shipEquipmentDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s shipEquipmentDo) Where(conds ...gen.Condition) *shipEquipmentDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s shipEquipmentDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *shipEquipmentDo {
	return s.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (s shipEquipmentDo) Order(conds ...field.Expr) *shipEquipmentDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s shipEquipmentDo) Distinct(cols ...field.Expr) *shipEquipmentDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s shipEquipmentDo) Omit(cols ...field.Expr) *shipEquipmentDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s shipEquipmentDo) Join(table schema.Tabler, on ...field.Expr) *shipEquipmentDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s shipEquipmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *shipEquipmentDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s shipEquipmentDo) RightJoin(table schema.Tabler, on ...field.Expr) *shipEquipmentDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s shipEquipmentDo) Group(cols ...field.Expr) *shipEquipmentDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s shipEquipmentDo) Having(conds ...gen.Condition) *shipEquipmentDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s shipEquipmentDo) Limit(limit int) *shipEquipmentDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s shipEquipmentDo) Offset(offset int) *shipEquipmentDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s shipEquipmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *shipEquipmentDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s shipEquipmentDo) Unscoped() *shipEquipmentDo {
	return s.withDO(s.DO.Unscoped())
}

func (s shipEquipmentDo) Create(values ...*model.ShipEquipment) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s shipEquipmentDo) CreateInBatches(values []*model.ShipEquipment, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s shipEquipmentDo) Save(values ...*model.ShipEquipment) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s shipEquipmentDo) First() (*model.ShipEquipment, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShipEquipment), nil
	}
}

func (s shipEquipmentDo) Take() (*model.ShipEquipment, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShipEquipment), nil
	}
}

func (s shipEquipmentDo) Last() (*model.ShipEquipment, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShipEquipment), nil
	}
}

func (s shipEquipmentDo) Find() ([]*model.ShipEquipment, error) {
	result, err := s.DO.Find()
	return result.([]*model.ShipEquipment), err
}

func (s shipEquipmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ShipEquipment, err error) {
	buf := make([]*model.ShipEquipment, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s shipEquipmentDo) FindInBatches(result *[]*model.ShipEquipment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s shipEquipmentDo) Attrs(attrs ...field.AssignExpr) *shipEquipmentDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s shipEquipmentDo) Assign(attrs ...field.AssignExpr) *shipEquipmentDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s shipEquipmentDo) Joins(fields ...field.RelationField) *shipEquipmentDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s shipEquipmentDo) Preload(fields ...field.RelationField) *shipEquipmentDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s shipEquipmentDo) FirstOrInit() (*model.ShipEquipment, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShipEquipment), nil
	}
}

func (s shipEquipmentDo) FirstOrCreate() (*model.ShipEquipment, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShipEquipment), nil
	}
}

func (s shipEquipmentDo) FindByPage(offset int, limit int) (result []*model.ShipEquipment, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s shipEquipmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s shipEquipmentDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s shipEquipmentDo) Delete(models ...*model.ShipEquipment) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *shipEquipmentDo) withDO(do gen.Dao) *shipEquipmentDo {
	s.DO = *do.(*gen.DO)
	return s
}
